name: project-echelon

services:
  server:
    build: 
      dockerfile: ./server.Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./packages/echelon-server/src
    healthcheck:
      test: "curl -f http://127.0.0.1:3000/health"
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "3000:3000"

  webui:
    build:
      dockerfile: ./webui.Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./packages/echelon-webui/src
    ports:
      - "8080:80"