name: project-echelon

services:
  server:
    build: 
      dockerfile: ./server.Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./packages/echelon-server/src
    healthcheck:
      test: "curl -f http://127.0.0.1:3000/health"
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "3000:3000"
    env_file: .env

  webui:
    build: 
      dockerfile: ./webui.Dockerfile
      args:
        API_BASE_URL: "http://localhost:3000"
    develop:
      watch:
        - action: rebuild
          path: ./packages/echelon-webui/src
    ports:
      - "8080:80"

  discord:
    build:
      dockerfile: ./discord.Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./packages/echelon-discord/src
    env_file: .env